---
title: "Data Visualization"
output: rmdformats::material
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 3DS : Cherry Blossom

## Lyuda Bekwinknoll, Meghana Cyanam, Theresa Marie Duenas, Kevin Kiser

# Loading and Cleaning Data

```{r, message = F}
# load packages
library(dplyr)
library(ggplot2)
library(lubridate)
library(chron)
library(plotly)
library(purrr)
library(RColorBrewer)
library(readr)
library(vroom)
```

```{r}

cb_5k_2006_2019_weather <- vroom("cb_5k_2006_2019_weather.csv", 
                                 col_types = cols(
  Year = col_double(),
  Name = col_character(),
  Age = col_integer(),
  Time = col_time(format = ""),
  Pace = col_time(format = ""),
  Division = col_character(),
  Hometown = col_character(),
  Distance = col_character(),
  pos_by_sex = col_integer(),
  total_by_sex = col_double(),
  pos_by_division = col_integer(), 
  total_by_division = col_double(),
  Sex = col_character(),
  DATE = col_date(format = "%Y-%m-%d"),
  PRCP = col_double(),
  TMAX = col_double(),
  TMIN = col_double()
))

cb_10M_1973_2005_weather <- vroom("cb_10M_1973_2005_weather.csv", 
                                 col_types = cols(
  Year = col_double(),
  Name = col_character(),
  Age = col_integer(),
  Time = col_time(format = ""),
  Pace = col_time(format = ""),
  Division = col_character(),
  Hometown = col_character(),
  Distance = col_character(),
  pos_by_sex = col_integer(),
  total_by_sex = col_double(),
  pos_by_division =col_integer(), 
  total_by_division = col_double(),
  Sex = col_character(),
  DATE = col_date(format = "%Y-%m-%d"),
  PRCP = col_double(),
  TMAX = col_double(),
  TMIN = col_double()
))

cb_10M_2006_2019_weather <- vroom("cb_10M_2006_2019_weather.csv", 
                                 col_types = cols(
  Year = col_double(),
  Name = col_character(),
  Age = col_integer(),
  Time = col_time(format = ""),
  Pace = col_time(format = ""),
  Division = col_character(),
  Hometown = col_character(),
  Distance = col_character(),
  pos_by_sex = col_integer(),
  total_by_sex = col_double(),
  pos_by_division = col_integer(), 
  total_by_division = col_double(),
  Sex = col_character(),
  DATE = col_date(format = "%Y-%m-%d"),
  PRCP = col_double(),
  TMAX = col_double(),
  TMIN = col_double()
))


combined_data <- bind_rows(
  cb_10M_1973_2005_weather,
  cb_10M_2006_2019_weather,
  cb_5k_2006_2019_weather
)

combined_data$Hometown[combined_data$Hometown == "NR"] <- NA
```

```{r}
cleaned_data <- combined_data %>%
  filter(!is.na(Age)) %>%
  filter(!is.na(Time) & Time != "")

# Remove any non-numeric and non-column characters from 'Time'
cleaned_data$Time <- gsub("[^0-9:]", "", cleaned_data$Time)

# Remove NA's from 'Time' 
cleaned_data <- cleaned_data[!is.na(cleaned_data$Time), , drop = FALSE]

# Remove empty strings from 'Time'
cleaned_data <- cleaned_data[cleaned_data$Time != '', , drop = FALSE]

# Converts 'Time' column to a time format
cleaned_data$Time <- chron::times(cleaned_data$Time)

# Removes any potential NA's generated from the conversion above
cleaned_data <- cleaned_data[!is.na(cleaned_data$Time), , drop = FALSE]

```

# Data Visualization
